allowBuilds:
  better-sqlite3: true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
