export const projectCardClassNames = {
  root: "group flex min-w-0 flex-col border-t border-border pt-5",
  cover: "relative aspect-[16/10] overflow-hidden rounded-[1.5rem] bg-subtle no-underline shadow-[0_18px_55px_rgb(39_39_42_/_0.1)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-vivid/60 focus-visible:ring-offset-4 focus-visible:ring-offset-bg",
  coverImage: "object-cover transition-transform duration-700 group-hover:scale-[1.035] motion-reduce:transition-none motion-reduce:transform-none",
  placeholder: "project-placeholder absolute inset-0 flex items-center justify-center",
  monogram: "font-mono text-[clamp(4rem,10vw,8rem)] font-semibold tracking-[-0.08em] text-white/90",
  body: "flex flex-1 flex-col pt-6",
  title: "text-balance text-3xl font-semibold leading-tight tracking-[-0.045em]",
  titleLink: "rounded-sm no-underline transition-colors hover:text-accent-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-vivid/60",
  description: "mt-3 max-w-xl text-pretty text-sm leading-7 text-muted",
  tags: "mt-5 flex flex-wrap gap-x-4 gap-y-2",
  tag: "rounded-sm font-mono text-[0.62rem] uppercase tracking-[0.1em] text-faint no-underline after:ml-4 after:text-border after:content-['/'] last:after:content-none transition-colors hover:text-accent-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-vivid/60",
  actions: "mt-6 flex flex-wrap items-center gap-x-4 gap-y-3 border-t border-border pt-5",
  mainAction: "rounded-sm text-sm font-medium text-muted no-underline transition-colors hover:text-accent-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-vivid/60",
  secondaryAction: "flex items-center gap-1 rounded-sm text-sm text-faint no-underline transition-colors hover:text-fg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-vivid/60",
} as const;
